# Application Configuration
server.port=8080

# Active Spring Profile
spring.profiles.active=local,aws

# File Upload configuration (Support up to 50MB for hackathon)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# AWS Configuration
aws.region=us-east-1

# Optional Local DynamoDB Endpoint for development (e.g. localhost:8000)
# aws.dynamodb.endpoint=http://localhost:8000

